[tool.poetry]
name = "docker-vscode-texdev"
version = "0.2.1"
description = "Docker container for use with VS Code"
license = "BSD-3-Clause"
authors = ["Andrew Teixeira <teixeira@broadinstitute.org>"]
readme = "README.md"
repository = "https://github.com/coreone/docker-vscode-texdev"
homepage = "https://github.com/coreone/docker-devnull-texdev"
keywords = ["docker", "vscode", "python", "ruby", "puppet", "terraform"]

[tool.poetry.dependencies]
python = "^3.7"  # Compatible python versions must be declared here

# Python specific dependencies with prereleases allowed
black = { version = "^19.0", allow-prereleases = true }
# 4.0.1 breaks for some reason
python-slugify = "<= 4.0.0"
# Git dependencies
scaraplate = "> 0.2"
toml = ">= 0.9"

bump2version = "*"
codecov = "*"
cookiecutter = "*"
coverage = "*"
fixtures = "*"
green = "*"
mock = "*"
pydocstyle = "*"
pylama = "*"
pylint = "*"
pyyaml = "*"
setuptools = "*"
testtools = "*"
twine = "*"
unittest2 = "*"
wheel = "*"
yamllint = "*"

#[tool.poetry.dev-dependencies]
